;-- Hammer sql file
CREATE DATABASE IF NOT EXISTS hammer;
USE hammer;
;-- Company table
CREATE TABLE IF NOT EXISTS Company(
ID INT NOT NULL AUTO_INCREMENT,
Name VARCHAR(255) NOT NULL,
Remark VARCHAR(1024),
PRIMARY KEY (ID)
)
;-- IP table
CREATE TABLE IF NOT EXISTS IP(
ID INT NOT NULL AUTO_INCREMENT,
Addr VARCHAR(16) NOT NULL,
Comp_ID INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (Comp_ID) REFERENCES Company(ID)
)
;-- Host table
CREATE TABLE IF NOT EXISTS Host(
ID INT NOT NULL AUTO_INCREMENT,
Value VARCHAR(255) NOT NULL,
Comp_ID INT NOT NULL,
IP_ID INT,
PRIMARY KEY (ID),
FOREIGN KEY (Comp_ID) REFERENCES Company(ID),
FOREIGN KEY (IP_ID) REFERENCES IP(ID)
)
;-- Port table
CREATE TABLE IF NOT EXISTS PORT(
ID INT NOT NULL AUTO_INCREMENT,
Value INT NOT NULL,
IP_ID INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (IP_ID) REFERENCES IP(ID)
)
