;-- Hammer sql file
CREATE DATABASE IF NOT EXISTS hammer DEFAULT CHARACTER SET utf8;
USE hammer;
;-- Company table
CREATE TABLE IF NOT EXISTS Company(
ID INT NOT NULL AUTO_INCREMENT,
Name VARCHAR(255) NOT NULL,
Remark VARCHAR(1024),
PRIMARY KEY (ID)
)
;-- IP table
CREATE TABLE IF NOT EXISTS IP(
ID INT NOT NULL AUTO_INCREMENT,
Addr VARCHAR(16) NOT NULL,
Comp_ID INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (Comp_ID) REFERENCES Company(ID)
)
;-- Host table
CREATE TABLE IF NOT EXISTS Host(
ID INT NOT NULL AUTO_INCREMENT,
Value VARCHAR(255) NOT NULL,
Comp_ID INT NOT NULL,
IP_ID INT,
PRIMARY KEY (ID),
FOREIGN KEY (Comp_ID) REFERENCES Company(ID),
FOREIGN KEY (IP_ID) REFERENCES IP(ID)
)
;-- Port table
CREATE TABLE IF NOT EXISTS PORT(
ID INT NOT NULL AUTO_INCREMENT,
Value INT NOT NULL,
IP_ID INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (IP_ID) REFERENCES IP(ID)
)
;-- Proxy interfaces
CREATE TABLE IF NOT EXISTS Proxy(
ID INT NOT NULL AUTO_INCREMENT,
IP_Addr VARCHAR(16) NOT NULL,
Port INT NOT NULL,
Http_Type VARCHAR(6) NOT NULL,
Address VARCHAR(1024) NOT NULL,
Time INT NOT NULL,
PRIMARY KEY(ID),
UNIQUE KEY URL(IP_Addr,Port,Http_Type)
)
;-- Scan table
CREATE TABLE IF NOT EXISTS Scan(
ID INT NOT NULL AUTO_INCREMENT,
Host_ID INT,
Arguments VARCHAR(1024) NOT NULL,
Result VARCHAR(20480),
PRIMARY KEY(ID),
FOREIGN KEY(Host_ID) REFERENCES Host(ID)
)